name: Archive Thumbnails Artifact

on:
  push:
    branches: [release, staging, preview]

  workflow_dispatch: null

jobs:
  prepare_media:
    runs-on: ubuntu-latest

    steps:
      - name: Install ImageMagick
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: imagemagick
          version: 1.0

      - name: Checkout corresponding canonical code repo
        uses: actions/checkout@v4
        with:
          repository: hsmusic/hsmusic-wiki
          ref: ${{ github.ref_name }}
          path: code

      - name: Checkout corresponding canonical data repo
        uses: actions/checkout@v4
        with:
          repository: hsmusic/hsmusic-data
          ref: ${{ github.ref_name }}
          path: data

      - name: Checkout media repo
        uses: actions/checkout@v4
        with:
          repository: hsmusic/hsmusic-media
          ref: ${{ github.ref }}
          path: media

      - name: Install code repository
        working-directory: ./code
        run: npm ci

      - name: Generate thumbnails
        run: |
          node code/src/upd8.js \
            --show-step-summary \
            --data-path data \
            --media-path media \
            --thumbs-only

      - name: Archive thumbnails artifact
        uses: actions/upload-artifact@v3
        with:
          name: media
          path: media
